services:
  postgres:
    image: postgres
    container_name: reading-goals-api
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reading-goals
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql
