name: Deploy

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          DATABASE_URL: 'postgresql://dummy:dummy@localhost:5432/dummy'

      - name: Generate Prisma client
        run: pnpm prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Eslint
        run: pnpm run eslint:check

      - name: Prettier
        run: pnpm run prettier:check

      - name: Start test database
        run: docker compose up -d --wait postgres-test

      - name: Run test migrations
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: 'postgresql://postgres:password@localhost:5433'

      - name: Test
        run: pnpm run test
        env:
          DATABASE_URL: 'postgresql://postgres:password@localhost:5433'
